"""collector と stdio reporter が共有する接続用の定数。

reporter の起動時に collector や CLI の実装を読み込まずに接続できるようにする。
"""

FEEDBACK_CAPABILITY_ENV = "CMOC_FEEDBACK_CAPABILITY"
FEEDBACK_COLLECTOR_HOST = "127.0.0.1"
FEEDBACK_COLLECTOR_PORT_ENV = "CMOC_FEEDBACK_COLLECTOR_PORT"
FEEDBACK_PROTOCOL_ENV = "CMOC_FEEDBACK_PROTOCOL_VERSION"
